[tool.poetry]
name = "paiclient"
version = "0.1.0"
description = ""
authors = ["LoryPelli"]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.2"
uvicorn = "^0.29.0"
openai = "^1.23.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
